creature+subclasses
akruglov18/ConsolGame pull request #23
Opened 2021-12-21 09:53 UTC by vladikganja

Added base class "creature" and child-classes of creatures such as "beetle", "taur", "wolf", "player".
Also added class of action for creatures
Additional: ResourseHolder -- a brilliant class for all multimedia

2021-12-21 16:17 UTC, akruglov18 requested changes

2021-12-21 16:17 UTC, akruglov18 commented on creature/enemyTaur/enemyTaur.cpp
> +}
сonst Texture*

2021-12-21 16:17 UTC, akruglov18 commented on field/field.cpp
>  }
x, y - don't reflect the meaning of variable

2021-12-21 16:17 UTC, akruglov18 commented on field/field.cpp
>      }
it may be better to pre-load all sprites and texture, then we will just use method 'getResource'?

2021-12-21 16:17 UTC, akruglov18 commented on field/field.h
const

2021-12-21 16:17 UTC, akruglov18 commented on tests/tiles_test.cpp
>  }
Please add more tests for tiles

2021-12-21 16:20 UTC, vladikganja commented on creature/Player/player.h
> +    sf::Sprite _sprite_hands;*/
it is exactly, it will be done soon

2021-12-21 16:25 UTC, akruglov18 commented
Check all methods, if variables of classes is immutable then declare these methods as const

2021-12-21 16:33 UTC, vladikganja commented on creature/creature.h
> +    static Creature* spawn_creature(CreatureType, sf::Texture*);
A bit strange because it is static method, it doesn't need const as I know

2021-12-22 11:05 UTC, akruglov18 requested changes

2021-12-22 11:21 UTC, akruglov18 approved these changes

2021-12-22 11:21 UTC, merged